author: 
  github_link: "https://github.com/davidbmitchell"
  name: "David B. Mitchell"
description: "Personal website of David B. Mitchell"
domain: davidbaileymitchell.com
excerpt_separator: "\n\n\n"
exclude: 
  - terminal.glue
highlighter: pygments
markdown: kramdown
name: "David Bailey Mitchell"
paginate: 10
paginate_path: "/blog/:num/"
permalink: "/post/:title"
relative_permalinks: true
url: "https://davidbaileymitchell.com"