permalink: /post/:title
exclude: [terminal.glue]
highlighter: pygments
markdown: kramdown
relative_permalinks: true

paginate: 10
paginate_path: '/blog/:num/'

excerpt_separator: "\n\n\n"

name: 'David Bailey Mitchell'
domain: davidbaileymitchell.com
url: https://davidbaileymitchell.com
description: 'Personal website of David B. Mitchell'
  name: David B. Mitchell
  github_link: https://github.com/davidbmitchell
