name: 'David B. Mitchell'
permalink: /post/:title
production_url: http://davidbaileymitchell.com
description: 'Baseball, Economics, Life, Game Theory, and Baseball All in One Place.'
exclude: [terminal.glue]
highlighter: pygments
markdown: kramdown
relative_permalinks: true

paginate: 10
paginate_path: '/blog/:num/'

excerpt_separator: "\n\n\n"